name: 'Generate Changelog'
description: 'Generate a changelog based on conventional commits'

outputs:
  changelog:
    description: 'The generated changelog'
runs:
  using: 'node16'
  main: 'lib/index.js'
