name: Build on push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Commit if something has changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'commiting build files'
          commit_options: '--no-verify'
          commit_user_name: GitHub Action
